export const errorTypes = {
  INVALID_INPUT: 'INVALID_INPUT',
  DUPLICATED_NICKNAME: 'DUPLICATED_NICKNAME',
  DUPLICATED_EMAIL: 'DUPLICATED_EMAIL',
  AUTHENTICATION_FAIL: 'AUTHENTICATION_FAIL',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND_RESOURCE: 'NOT_FOUND_RESOURCE',
  NOT_MATCH_PASSWORD: 'NOT_MATCH_PASSWORD',
  NOT_LOGIN_MEMBER: 'NOT_LOGIN_MEMBER',
  INVALID_MEMBER: 'INVALID_MEMBER ',
  UNHANDLED_ERROR: 'UNHANDLED_ERROR',
  ALREADY_PARTICIPATE_GROUP: 'ALREADY_PARTICIPATE_GROUP',
  AUTHORIZATION_FAIL: 'AUTHORIZATION_FAIL',
};
