export const errorType = {
  INVALID_INPUT: 'INVALID_INPUT',
  DUPLICATED_NICKNAME: 'DUPLICATED_NICKNAME',
  DUPLICATED_EMAIL: 'DUPLICATED_EMAIL',
  AUTHENTICATION_FAIL: 'AUTHENTICATION_FAIL',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export const tagList = [];
